=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/templates/schema_v1.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "taskName",
    "tableName",
    "columns",
    "steps",
    "version"
  ],
  "properties": {
    "taskName": {
      "$id": "#/properties/taskName",
      "type": "string",
      "title": "The Taskname Schema",
      "default": "",
      "examples": [
        "daily_salary_activate"
      ],
      "pattern": "^(.*)$"
    },
    "tableName": {
      "$id": "#/properties/tableName",
      "type": "string",
      "title": "The Tablename Schema",
      "default": "",
      "examples": [
        "daily_salary_activate"
      ],
      "pattern": "^(.*)$"
    },
    "columns": {
      "$id": "#/properties/columns",
      "type": "array",
      "title": "The Columns Schema",
      "items": {
        "$id": "#/properties/columns/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "name",
          "type"
        ],
        "properties": {
          "name": {
            "$id": "#/properties/columns/items/properties/name",
            "type": "string",
            "title": "The Name Schema",
            "default": "",
            "examples": [
              "total_register_amount"
            ],
            "pattern": "^(.*)$"
          },
          "type": {
            "$id": "#/properties/columns/items/properties/type",
            "type": "string",
            "title": "The Type Schema",
            "default": "",
            "examples": [
              "long"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "steps": {
      "$id": "#/properties/steps",
      "type": "array",
      "title": "The Steps Schema",
      "items": {
        "$id": "#/properties/steps/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "sql",
          "tempView",
          "macros"
        ],
        "properties": {
          "sql": {
            "$id": "#/properties/steps/items/properties/sql",
            "type": "string",
            "title": "The Sql Schema",
            "default": "",
            "examples": [
              "SELECT eqi.certid certid,max(eqi.logts) as logts from mysql_hxdb_employee_quota_info eqi where eqi.quotastatus!='6' GROUP BY eqi.certid"
            ],
            "pattern": "^(.*)$"
          },
          "tempView": {
            "$id": "#/properties/steps/items/properties/tempView",
            "type": "string",
            "title": "The Tempview Schema",
            "default": "",
            "examples": [
              "m"
            ],
            "pattern": "^(.*)$"
          },
          "macros": {
            "$id": "#/properties/steps/items/properties/macros",
            "type": "object",
            "title": "The Macros Schema"
          }
        }
      }
    },
    "version": {
      "$id": "#/properties/version",
      "type": "string",
      "title": "The Version Schema",
      "default": "",
      "examples": [
        "1.0"
      ],
      "pattern": "^(.*)$"
    }
  }
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/salary_ipebg_count_day.json
{
  "taskName": "salary_ipebg_count_day",
  "tableName": "salary_ipebg_count",
  "columns": [
    {
      "name": "count",
      "type": "long"
    },
    {
      "name": "type",
      "type": "string"
    }
  ],
  "steps": [
    {
      "sql": "SELECT count(*) as count,'day' as type FROM foxconn_ipebg_group_salary WHERE unix_timestamp(create_time,'yyyyMMddHHmmss')>=unix_timestamp('#{biz_date}', 'yyyyMMdd')",
      "tempView": "m",
      "macros": {
        "#{biz_date}": ""
      }
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/salary_fii_ct_count.json
{
  "taskName": "salary_fii_ct_count",
  "tableName": "salary_fii_ct_count",
  "columns": [
    {
      "name": "count",
      "type": "long"
    },
    {
      "name": "type",
      "type": "string"
    }
  ],
  "steps": [
    {
      "sql": "SELECT COUNT(*) as count,'total' as type FROM (SELECT DISTINCT emp_no FROM foxconn_fii_group_salary_cnsgb_tsbg) t",
      "tempView": "t",
      "macros": {}
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/salary_idpbg_count_day.json
{
  "taskName": "salary_idpbg_count_day",
  "tableName": "salary_idpbg_count",
  "columns": [
    {
      "name": "count",
      "type": "long"
    },
    {
      "name": "type",
      "type": "string"
    }
  ],
  "steps": [
    {
      "sql": "SELECT count(*) as count,'day' as type FROM foxconn_idpgidpbg_group_salary WHERE unix_timestamp(create_time,'yyyyMMddHHmmss')>=unix_timestamp('#{biz_date}', 'yyyyMMdd')",
      "tempView": "m",
      "macros": {
        "#{biz_date}": ""
      }
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/daily_salary_activate.json
{
  "taskName": "daily_salary_activate",
  "tableName": "daily_salary_activate",
  "columns": [
    {
      "name": "total_register_amount",
      "type": "long"
    },
    {
      "name": "activate_salary_amount",
      "type": "long"
    },
    {
      "name": "biz_date",
      "type": "string"
    },
    {
      "name": "begin_time",
      "type": "date"
    },
    {
      "name": "end_time",
      "type": "date"
    }
  ],
  "steps": [
    {
      "sql": "SELECT eqi.certid certid,max(eqi.logts) as logts from mysql_hxdb_employee_quota_info eqi where eqi.quotastatus!='6' GROUP BY eqi.certid",
      "tempView": "m",
      "macros": {}
    },
    {
      "sql": "select eqi1.certid,eqi1.quotastatus from mysql_hxdb_employee_quota_info eqi1, m where m.certid=eqi1.certid and m.logts=eqi1.logts",
      "tempView": "t",
      "macros": {}
    },
    {
      "sql":"SELECT count(*) as total_register_amount,sum(case when t.quotastatus=2 then 1 end) as activate_salary_amount,#{biz_date} as biz_date, #{begin_time} as begin_time, #{end_time} as end_time from t",
      "tempView": "fa",
      "macros": {
        "#{biz_date}": "",
        "#{begin_time}": "",
        "#{end_time}": ""
      }
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/salary_h_count.json
{
  "taskName": "salary_h_count",
  "tableName": "salary_h_count",
  "columns": [
    {
      "name": "count",
      "type": "long"
    },
    {
      "name": "type",
      "type": "string"
    }
  ],
  "steps": [
    {
      "sql": "SELECT COUNT(*) as count,'total' as type FROM (SELECT DISTINCT emp_no FROM foxconn_h_group_salary_one) t",
      "tempView": "t",
      "macros": {}
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/daily_salary_daily_consume_amt.json
{
  "taskName": "daily_salary_daily_consume_amt",
  "tableName": "daily_salary_daily_consume_amt",
  "columns": [
    {
      "name": "sjtname",
      "type": "string"
    },
    {
      "name": "daily_consume_amt",
      "type": "double"
    },
    {
      "name": "biz_date",
      "type": "string"
    },
    {
      "name": "begin_time",
      "type": "date"
    },
    {
      "name": "end_time",
      "type": "date"
    }
  ],
  "steps": [
    {
      "sql":"select sjtname, sum(currentusedquota) as daily_consume_amt,#{biz_date} as biz_date,#{begin_time} as begin_time,#{end_time} as end_time from mysql_hxdb_employee_quota_uselog where to_date(inputtime) = from_unixtime(${endDateTime}/1000, 'yyyy-MM-dd') group by sjtname",
      "tempView": "",
      "macros": {
        "#{biz_date}": "",
        "${endDateTime}":"",
        "#{begin_time}": "",
        "#{end_time}": ""
      }
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/salary_idpbg_count.json
{
  "taskName": "salary_idpbg_count",
  "tableName": "salary_idpbg_count",
  "columns": [
    {
      "name": "count",
      "type": "long"
    },
    {
      "name": "type",
      "type": "string"
    }
  ],
  "steps": [
    {
      "sql": "SELECT COUNT(*) as count,'total' as type FROM (SELECT DISTINCT emp_no FROM foxconn_idpgidpbg_group_salary) t",
      "tempView": "t",
      "macros": {}
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/salary_fii_cesgb_count.json
{
  "taskName": "salary_fii_cesgb_count",
  "tableName": "salary_fii_cesgb_count",
  "columns": [
    {
      "name": "count",
      "type": "long"
    },
    {
      "name": "type",
      "type": "string"
    }
  ],
  "steps": [
    {
      "sql": "SELECT COUNT(*) as count,'total' as type FROM (SELECT DISTINCT emp_no FROM foxconn_fii_group_salary_cesgb) t",
      "tempView": "t",
      "macros": {}
    }
  ],
  "version": "1.0"
}
