=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/templates/schema_v2.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "taskName",
    "dataSource",
    "targetDest",
    "steps",
    "extra",
    "version"
  ],
  "properties": {
    "taskName": {
      "$id": "#/properties/taskName",
      "type": "string",
      "title": "The Taskname Schema",
      "default": "",
      "examples": [
        "template"
      ],
      "pattern": "^(.*)$"
    },
    "dataSource": {
      "$id": "#/properties/dataSource",
      "type": "object",
      "title": "The Datasource Schema",
      "required": [
        "sourceName",
        "dbName"
      ],
      "properties": {
        "sourceName": {
          "$id": "#/properties/dataSource/properties/sourceName",
          "type": "string",
          "title": "The Sourcename Schema",
          "default": "",
          "examples": [
            "Hive"
          ],
          "pattern": "^(.*)$"
        },
        "dbName": {
          "$id": "#/properties/dataSource/properties/dbName",
          "type": "string",
          "title": "The Dbname Schema",
          "default": "",
          "examples": [
            "db_0"
          ],
          "pattern": "^(.*)$"
        }
      }
    },
    "targetDest": {
      "$id": "#/properties/targetDest",
      "type": "object",
      "title": "The Targetdest Schema",
      "required": [
        "targetName",
        "dbName",
        "tableName",
        "columns"
      ],
      "properties": {
        "targetName": {
          "$id": "#/properties/targetDest/properties/targetName",
          "type": "string",
          "title": "The Targetname Schema",
          "default": "",
          "examples": [
            "Hive"
          ],
          "pattern": "^(.*)$"
        },
        "dbName": {
          "$id": "#/properties/targetDest/properties/dbName",
          "type": "string",
          "title": "The Dbname Schema",
          "default": "",
          "examples": [
            "db_1"
          ],
          "pattern": "^(.*)$"
        },
        "tableName": {
          "$id": "#/properties/targetDest/properties/tableName",
          "type": "string",
          "title": "The Tablename Schema",
          "default": "",
          "examples": [
            "abc12"
          ],
          "pattern": "^(.*)$"
        },
        "columns": {
          "$id": "#/properties/targetDest/properties/columns",
          "type": "array",
          "title": "The Columns Schema",
          "items": {
            "$id": "#/properties/targetDest/properties/columns/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "fieldName",
              "fieldType"
            ],
            "properties": {
              "fieldName": {
                "$id": "#/properties/targetDest/properties/columns/items/properties/fieldName",
                "type": "string",
                "title": "The Fieldname Schema",
                "default": "",
                "examples": [
                  "id"
                ],
                "pattern": "^(.*)$"
              },
              "fieldType": {
                "$id": "#/properties/targetDest/properties/columns/items/properties/fieldType",
                "type": "string",
                "title": "The Fieldtype Schema",
                "default": "",
                "examples": [
                  "string"
                ],
                "pattern": "^(.*)$"
              }
            }
          }
        }
      }
    },
    "steps": {
      "$id": "#/properties/steps",
      "type": "array",
      "title": "The Steps Schema",
      "items": {
        "$id": "#/properties/steps/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "sql",
          "tempView",
          "macros"
        ],
        "properties": {
          "sql": {
            "$id": "#/properties/steps/items/properties/sql",
            "type": "string",
            "title": "The Sql Schema",
            "default": "",
            "examples": [
              "select a,b,c from tableA where logts >= ${startDateTime} and logts < ${endDateTime}"
            ],
            "pattern": "^(.*)$"
          },
          "tempView": {
            "$id": "#/properties/steps/items/properties/tempView",
            "type": "string",
            "title": "The Tempview Schema",
            "default": "",
            "examples": [
              "t1"
            ],
            "pattern": "^(.*)$"
          },
          "macros": {
            "$id": "#/properties/steps/items/properties/macros",
            "type": "object",
            "title": "The Macros Schema"
          }
        }
      }
    },
    "extra": {
      "$id": "#/properties/extra",
      "type": "object",
      "title": "The Extra Schema"
    },
    "version": {
      "$id": "#/properties/version",
      "type": "string",
      "title": "The Version Schema",
      "default": "",
      "examples": [
        "2.0"
      ],
      "pattern": "^(.*)$"
    }
  }
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/scripts/test.json
{
  "taskName":"test",
  "dataSource": {
    "sourceName":"Hive",
    "dbName":"fox_data"
  },
  "targetDest": {
    "targetName": "MySQL",
    "dbName":"`fox-data-bi`",
    "tableName":"v2_test",
    "columns": [
      {
        "fieldName":"sjt_name",
        "fieldType":"string"
      },
      {
        "fieldName":"class_name",
        "fieldType":"string"
      },
      {
        "fieldName":"fac_name",
        "fieldType":"string"
      }
    ]
  },
  "steps":[
    {
      "sql":"select sjtname as sjt_name,classname as class_name,facname as fac_name from fox_data.mysql_hxdb_employee_info where partition_month='2019-03' group by sjtname,classname,facname",
      "tempView":"t1",
      "macros": {}
    }
  ],
  "extra": {},
  "version":"2.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/scripts/test_hive.json
{
  "taskName":"test_hive",
  "dataSource": {
    "sourceName":"Hive",
    "dbName":"fox_data"
  },
  "targetDest": {
    "targetName": "Hive",
    "dbName":"`fox_data`",
    "tableName":"test02",
    "columns": [
      {
        "fieldName":"sjt_name",
        "fieldType":"string"
      },
      {
        "fieldName":"class_name",
        "fieldType":"string"
      },
      {
        "fieldName":"fac_name",
        "fieldType":"string"
      }
    ]
  },
  "steps":[
    {
      "sql":"select sjtname as sjt_name,classname as class_name,facname as fac_name,#{partition_month} as partition_month from fox_data.mysql_hxdb_employee_info where partition_month='2019-03' group by sjtname,classname,facname",
      "tempView":"t1",
      "macros": {
        "#{partition_month}": ""
      }
    }
  ],
  "extra": {
    "partitionFieldName": "partition_month",
    "partitionStrategy": "month",
    "saveMode": "append",
    "saveFormat": "hive"
  },
  "version":"2.0"
}
