=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/templates/schema_v1.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "taskName",
    "tableName",
    "columns",
    "steps",
    "version"
  ],
  "properties": {
    "taskName": {
      "$id": "#/properties/taskName",
      "type": "string",
      "title": "The Taskname Schema",
      "default": "",
      "examples": [
        "daily_salary_activate"
      ],
      "pattern": "^(.*)$"
    },
    "tableName": {
      "$id": "#/properties/tableName",
      "type": "string",
      "title": "The Tablename Schema",
      "default": "",
      "examples": [
        "daily_salary_activate"
      ],
      "pattern": "^(.*)$"
    },
    "columns": {
      "$id": "#/properties/columns",
      "type": "array",
      "title": "The Columns Schema",
      "items": {
        "$id": "#/properties/columns/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "name",
          "type"
        ],
        "properties": {
          "name": {
            "$id": "#/properties/columns/items/properties/name",
            "type": "string",
            "title": "The Name Schema",
            "default": "",
            "examples": [
              "total_register_amount"
            ],
            "pattern": "^(.*)$"
          },
          "type": {
            "$id": "#/properties/columns/items/properties/type",
            "type": "string",
            "title": "The Type Schema",
            "default": "",
            "examples": [
              "long"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "steps": {
      "$id": "#/properties/steps",
      "type": "array",
      "title": "The Steps Schema",
      "items": {
        "$id": "#/properties/steps/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "sql",
          "tempView",
          "macros"
        ],
        "properties": {
          "sql": {
            "$id": "#/properties/steps/items/properties/sql",
            "type": "string",
            "title": "The Sql Schema",
            "default": "",
            "examples": [
              "SELECT eqi.certid certid,max(eqi.logts) as logts from mysql_hxdb_employee_quota_info eqi where eqi.quotastatus!='6' GROUP BY eqi.certid"
            ],
            "pattern": "^(.*)$"
          },
          "tempView": {
            "$id": "#/properties/steps/items/properties/tempView",
            "type": "string",
            "title": "The Tempview Schema",
            "default": "",
            "examples": [
              "m"
            ],
            "pattern": "^(.*)$"
          },
          "macros": {
            "$id": "#/properties/steps/items/properties/macros",
            "type": "object",
            "title": "The Macros Schema"
          }
        }
      }
    },
    "version": {
      "$id": "#/properties/version",
      "type": "string",
      "title": "The Version Schema",
      "default": "",
      "examples": [
        "1.0"
      ],
      "pattern": "^(.*)$"
    }
  }
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/daily_salary_group_complete_pct.json
{
  "taskName": "daily_salary_group_complete_pct",
  "tableName": "daily_salary_group_complete_pct",
  "columns": [
    {
      "name": "sjtname",
      "type": "string"
    },
    {
      "name": "active_amt",
      "type": "long"
    },
    {
      "name": "biz_date",
      "type": "string"
    },
    {
      "name": "begin_time",
      "type": "date"
    },
    {
      "name": "end_time",
      "type": "date"
    }
  ],
  "steps": [
    {
      "sql":"select count(distinct a.employeenum) as active_amt, a.sjtname, #{biz_date} as biz_date,#{begin_time} as begin_time,#{end_time} as end_time from (select employeenum, quotastatus, rank() over (partition by employeenum order by logts desc) as num, sjtname from mysql_hxdb_employee_quota_info where quotastatus != 6) a where a.num = 1 and a.quotastatus = 2 group by sjtname",
      "tempView": "",
      "macros": {
        "#{biz_date}": "",
        "${endDateTime}":"",
        "#{begin_time}": "",
        "#{end_time}": ""
      }
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/salary_b_count_day.json
{
  "taskName": "salary_b_count_day",
  "tableName": "salary_b_count",
  "columns": [
    {
      "name": "count",
      "type": "long"
    },
    {
      "name": "type",
      "type": "string"
    }
  ],
  "steps": [
    {
      "sql": "SELECT count(*) as count,'day' as type FROM foxconn_b_group_salary WHERE unix_timestamp(create_time,'yyyyMMddHHmmss')>=unix_timestamp('#{biz_date}', 'yyyyMMdd')",
      "tempView": "m",
      "macros": {
        "#{biz_date}": ""
      }
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/salary_h_count_day.json
{
  "taskName": "salary_h_count_day",
  "tableName": "salary_h_count",
  "columns": [
    {
      "name": "count",
      "type": "long"
    },
    {
      "name": "type",
      "type": "string"
    }
  ],
  "steps": [
    {
      "sql": "SELECT count(*) as count,'day' as type FROM foxconn_h_group_salary_one WHERE unix_timestamp(create_time,'yyyyMMddHHmmss')>=unix_timestamp('#{biz_date}', 'yyyyMMdd')",
      "tempView": "m",
      "macros": {
        "#{biz_date}": ""
      }
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/daily_salary_total_consume_amt.json
{
  "taskName": "daily_salary_total_consume_amt",
  "tableName": "daily_salary_total_consume_amt",
  "columns": [
    {
      "name": "sjtname",
      "type": "string"
    },
    {
      "name": "total_consume_amt",
      "type": "double"
    },
    {
      "name": "biz_date",
      "type": "string"
    },
    {
      "name": "begin_time",
      "type": "date"
    },
    {
      "name": "end_time",
      "type": "date"
    }
  ],
  "steps": [
    {
      "sql":"select bct2.businesstype,bct2.serialno from mysql_hxdb_business_contract bct2,(select bct.serialno,max(bct.logts) logts from mysql_hxdb_business_contract bct group by serialno) bct1 where bct2.serialno = bct1.serialno and bct2.logts = bct1.logts",
      "tempView": "bc",
      "macros": {}
    },
    {
      "sql":"select bpt2.serialno,bpt2.contractserialno,bpt2.putoutstatus from mysql_hxdb_business_putout bpt2,(select bpt.serialno,max(bpt.logts) logts from mysql_hxdb_business_putout bpt  group by serialno) bpt1 where bpt2.serialno = bpt1.serialno and bpt2.logts = bpt1.logts",
      "tempView": "bp",
      "macros": {}
    },
    {
      "sql":"select distinct bc.serialno,(case when eg.sjtname='FG' then'FII' else  eg.sjtname end) sjtname,eg.currentusedquota from mysql_hxdb_employee_quota_uselog eg, bc,bp,mysql_hxdb_code_library c where eg.contractno=bc.serialno and bc.businesstype='9' and bc.serialno=bp.contractserialno and bp.putoutstatus not in('06','07','10') and c.codeno='PutOutStatus' and c.itemno= bp.putoutstatus and eg.sjtname not in('H','J')",
      "tempView": "consumption_log",
      "macros": {}
    },
    {
      "sql":"select cl.sjtname as sjtname,sum(cl.currentusedquota) as total_consume_amt,#{biz_date} as biz_date,#{begin_time} as begin_time,#{end_time} as end_time from consumption_log cl group by cl.sjtname",
      "tempView": "",
      "macros": {
        "#{biz_date}": "",
        "#{begin_time}": "",
        "#{end_time}": ""
      }
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/daily_salary_total_consume_cnt.json
{
  "taskName": "daily_salary_total_consume_cnt",
  "tableName": "daily_salary_total_consume_cnt",
  "columns": [
    {
      "name": "sjtname",
      "type": "string"
    },
    {
      "name": "total_consume_cnt",
      "type": "long"
    },
    {
      "name": "biz_date",
      "type": "string"
    },
    {
      "name": "begin_time",
      "type": "date"
    },
    {
      "name": "end_time",
      "type": "date"
    }
  ],
  "steps": [
    {
      "sql":"select sjtname, count(currentusedquota) as total_consume_cnt, #{biz_date} as biz_date,#{begin_time} as begin_time,#{end_time} as end_time from mysql_hxdb_employee_quota_uselog group by sjtname",
      "tempView": "",
      "macros": {
        "#{biz_date}": "",
        "#{begin_time}": "",
        "#{end_time}": ""
      }
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/salary_ipebg_count.json
{
  "taskName": "salary_ipebg_count",
  "tableName": "salary_ipebg_count",
  "columns": [
    {
      "name": "count",
      "type": "long"
    },
    {
      "name": "type",
      "type": "string"
    }
  ],
  "steps": [
    {
      "sql": "SELECT COUNT(*) as count,'total' as type FROM (SELECT DISTINCT emp_no FROM foxconn_ipebg_group_salary) t",
      "tempView": "t",
      "macros": {}
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/daily_salary_fbd_consume_money.json
{
  "taskName": "daily_salary_fbd_consume_money",
  "tableName": "fbd_consume_money",
  "columns": [
    {
      "name": "amt_type",
      "type": "string"
    },
    {
      "name": "type_name",
      "type": "string"
    },
    {
      "name": "amount",
      "type": "double"
    },
    {
      "name": "biz_date",
      "type": "string"
    },
    {
      "name": "biz_hour",
      "type": "int"
    }
  ],
  "steps": [
    {
      "sql": "select distinct bcc.serialno,bcc.applyserialno,bcc.businesstype from mysql_hxdb_business_contract bcc,(select serialno,max(logts) logts from mysql_hxdb_business_contract group by serialno) unique where bcc.serialno = unique.serialno and bcc.logts = unique.logts  and bcc.dmltype in ('INSERT','UPDATE')",
      "tempView": "bc",
      "macros": {}
    },
    {
      "sql": "SELECT DISTINCT bp1.contractserialno,bp1.putoutstatus  from mysql_hxdb_business_putout bp1,(select contractserialno,max(logts) logts from mysql_hxdb_business_putout group by contractserialno) bp2 where bp1.contractserialno = bp2.contractserialno and bp1.logts = bp2.logts and bp1.dmltype in ('INSERT','UPDATE')",
      "tempView": "bp",
      "macros": {}
    },
    {
      "sql": "SELECT DISTINCT ba1.serialno,coalesce(ba1.businesssum,0.0) business_sum,(case when ba1.businesstype = '5' then '01' when ba1.businesstype in ('3','4') then '02' else '其他' end) as cnt_type,ba1.businesstype business_type from mysql_hxdb_business_apply ba1,(select serialno,max(logts) logts from mysql_hxdb_business_apply group by serialno) ba2 where ba1.serialno = ba2.serialno and ba1.logts = ba2.logts and regexp_replace(ba1.occurdate,'\\\\/','') = (case when #{biz_hour} = -1 then #{biz_date}-1 else #{biz_date} end) and ba1.businesstype in ('3','5','4')  and ba1.approvestatus = '03'",
      "tempView": "ba",
      "macros": {
        "#{biz_date}": "",
        "#{biz_hour}": ""
      }
    },
    {
      "sql": "select distinct bc.serialno,coalesce(eg.currentusedquota,0.0) current_used_quota  from (SELECT distinct  eg1.contractno,eg1.sjtname,eg1.currentusedquota from mysql_hxdb_employee_quota_uselog eg1,(select contractno,max(logts) logts from mysql_hxdb_employee_quota_uselog group by contractno) eg2 where eg1.contractno = eg2.contractno and eg1.logts = eg2.logts and regexp_replace(substr(eg1.inputtime,1,10),'\\\\-','')= (case when #{biz_hour} = -1 then #{biz_date}-1 else #{biz_date} end) and eg1.sjtname not in('H','J') )eg,bc,bp,mysql_hxdb_code_library c  where eg.contractno=bc.serialno and bc.businesstype='9' and bc.serialno=bp.contractserialno and c.codeno='PutOutStatus' and c.itemno=bp.putoutstatus  and bp.putoutstatus not in('06','07','10')",
      "tempView": "salaryPay",
      "macros": {
        "#{biz_date}": "",
        "#{biz_hour}": ""
      }
    },
    {
      "sql":"select ba.cnt_type amt_type,(case when ba.cnt_type = '01' then '提现' else '信用支付' end) as type_name, sum(case when ba.business_type = '5' then ba.business_sum when ba.business_type in ('3','4')  then (ba.business_sum) else 0.0 end) amount,(case when #{biz_hour} = -1 then #{biz_date}-1 else #{biz_date} end) as biz_date,(case when #{biz_hour} = -1 then 23 else #{biz_hour}  end) as biz_hour from  ba,bc,bp where ba.serialno = bc.applyserialno and bc.serialno = bp.contractserialno and bp.putoutstatus not in ('06', '07', '10')  group by ba.cnt_type   union all   SELECT  '03' as amt_type,'薪资支付' as type_name,  sum(salaryPay.current_used_quota) amount,(case when #{biz_hour} = -1 then #{biz_date}-1 else #{biz_date} end) as biz_date,(case when #{biz_hour} = -1 then 23 else #{biz_hour}  end) as biz_hour from    salaryPay",
      "tempView": "daily_salary_fbd_consume_money",
      "macros": {
        "#{biz_date}": "",
        "#{biz_hour}": ""
      }
    }
  ],
  "version": "1.0"
}

=== soon14/bdp-gold/gold-realtime/data-spark-process/data-hive/src/main/resources/table_mappings/salary_d_count.json
{
  "taskName": "salary_d_count",
  "tableName": "salary_d_count",
  "columns": [
    {
      "name": "count",
      "type": "long"
    },
    {
      "name": "type",
      "type": "string"
    }
  ],
  "steps": [
    {
      "sql": "SELECT COUNT(*) as count,'total' as type FROM (SELECT DISTINCT emp_no FROM foxconn_d_group_salary_new_pcebg) t",
      "tempView": "t",
      "macros": {}
    }
  ],
  "version": "1.0"
}
